tests/streaming/agent/test_utils.py

TODO: Migrate out the test cases later

Comment out utils to ignore deprecated OpenAIObject

---

vocode/streaming/agent/utils.py
vocode/streaming/synthesizer/azure_synthesizer.py

Check if the last word in the buffer is longer than 3 letters so that honorifics don't get stopped on as the last part of the chunk. Change silence type to comma-exact with 50 ms silence

Increase buffer; change azure synth silence

---

vocode/streaming/models/telephony.py
vocode/streaming/models/transcriber.py
vocode/streaming/transcriber/deepgram_transcriber.py

Currently, we are using time based endpointing
In this case, we are classifying the user's responses to see if they are done talking

Classify response made by user

---

vocode/streaming/agent/chat_gpt_agent.py
vocode/streaming/streaming_conversation.py
vocode/streaming/transcriber/deepgram_transcriber.py

We mute on is_final to prevent buffering into a second message Add in additional code cleaning

Stop speaking

---

vocode/streaming/agent/chat_gpt_agent.py
vocode/streaming/models/agent.py
vocode/streaming/streaming_conversation.py

still in progress waiting on hasura stuff and more testing.

remove language handling from vocode

---

vocode/streaming/streaming_conversation.py

interruptions first message fix

---

vocode/streaming/telephony/conversation/outbound_call.py

[autocaller pr](https://github.com/greymatter-labs/autocaller/pull/853)

update outbound call model

---

vocode/streaming/agent/state_agent.py

supports the schema changes in https://github.com/greymatter-labs/autocaller/pull/867

support options state

---

vocode/streaming/agent/state_agent.py
vocode/streaming/models/state_agent_transcript.py

"tested" by adding this script to the bottom of `state_agent_transcript.py` and running that file in isolation
```
dict = {"hi": "there"}
reg = StateAgentTranscriptEntry(role="reg", message="transcript entry")
print(reg)
invoke = StateAgentTranscriptActionInvoke(
state_id="invoke state", action_name=dict.get("test", "action has no name")
)
print(invoke)
try:
test = dict["bdsfsd"]
except Exception as e:
err = StateAgentTranscriptActionError(
action_name=None or "action has no name",
message=f"failed. dict is {dict}",
raw_error_message=str(e),
)
print(err)
state = StateAgentTranscriptHandleState(state_id="state id")
print(state)
iv = StateAgentTranscriptInvariantViolation(message=f"invariant! {dict}")
print(iv)
```
prints
```
role='reg' message='transcript entry' …
```

more info in json transcripts

---

vocode/streaming/agent/state_agent.py
vocode/streaming/streaming_conversation.py
vocode/streaming/transcriber/deepgram_transcriber.py

type a being bot interrupts you

Add vad for type a interruption prevention

---

vocode/streaming/agent/state_agent.py

this fixes multi step blocks because we use json to resume in chat but it always ends up back at the start state.

make it set the resume function too

---

vocode/streaming/agent/base_agent.py
vocode/streaming/streaming_conversation.py

pass ctx to agent

---

vocode/streaming/streaming_conversation.py

1. To prevent logging of messages that got cancelled, moved logging to *after* speech synthesis which should improve or fix the issue.
2. To try to prevent infinite hanging with background noise, I made the idle task raise the VAD threshold if a 4 second silence is detected.
3. Should fix interruptibility of first message on outbound by making it non blocking to send.

improve_transcription_behavior

---

vocode/streaming/action/create_sunshine_conversation_after_call.py
vocode/streaming/action/factory.py
vocode/streaming/models/actions.py
vocode/streaming/utils/setup_command_r_tools.py

test call without the new action: https://app.opencall.ai/console/calls/WzEsICJwdWJsaWMiLCAiaW5ib3VuZF9jYWxscyIsIDQ5MTg1XQ%3D%3D

sunshine convo after call action

---

vocode/streaming/agent/state_agent.py

first call: https://app.opencall.ai/console/calls/WzEsICJwdWJsaWMiLCAiaW5ib3VuZF9jYWxscyIsIDUyNjk1XQ%3D%3D
second call: https://app.opencall.ai/console/calls/WzEsICJwdWJsaWMiLCAiaW5ib3VuZF9jYWxscyIsIDUyNjk5XQ%3D%3D

fix memory persistence

---

vocode/streaming/transcriber/deepgram_transcriber.py

Remove the vad stats, no reason to record them in that manner. Did it initially for debugging and ig it slipped through review.
[ticket](https://linear.app/greymatter/issue/GRE-1144/fix-division-by-zero-in-vad-stats)

remove vad stats

---

vocode/streaming/models/agent.py

tested an inbound and outbound call on a fresh agent. No errors.

mark prompt preamble optional

---

vocode/streaming/agent/state_agent.py
vocode/streaming/streaming_conversation.py

Potentially mitigates the need for adjustable response delay.
Attempts to fix the bot interrupting the user after a couple of words via _automatic_ response delay adjustment.
Splits sleep into three components:
a. up to 1 second based on the endpoint classifier's confidence (already in place)
+
b. up to 1 second based on the inverse of the average model latency (lower latency, longer sleep) (doesn't impact if model latency on avg is > 1 second already)
+ 
c. up to 1 second delay proportional to the length of the user's response (does not impact 95% of responses)

Attempt to add automatic response delay

---

vocode/streaming/agent/state_agent.py

follow up to https://github.com/greymatter-labs/vocode-python-main/pull/373/commits/1f89e19aa6856e8b117871e51ad658eda5315a08#r1868294874

deserialize resume

---

vocode/streaming/output_device/base_output_device.py

should improve linting. No behavioral changes

use abc for base output device
